name: Deploy Github Pages with Azure

on:
  push:
    branches:
      - main
      - stage
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code #Sirve para ubicarme en el repositorio de la maquina virtual
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # - name: Create file
      #   run: ssh -o StrictHostKeyChecking=no azureuser@20.55.25.47 touch hola.txt

      - name: Deploy to stage Server
        if : ${{ github.ref == 'refs/heads/stage' }}
        run: bash deploy.sh stage
        working-directory: Exercises/c6

      - name: Deploy to prod Server
        if : ${{ github.ref == 'refs/heads/main' }}
        run: bash deploy.sh main
        working-directory: Exercises/c6
